<a href="https://colab.research.google.com/github/ZChiqui/ML-models-comparison/blob/main/churn_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install --upgrade google-cloud-bigquery

# I used my cloud storage but you will find the csv in the project to do the same

In [ ]:
# from google.colab import auth
# auth.authenticate_user()

# from google.cloud import bigquery


# # Usá el ID de tu proyecto de GCP
# PROJECT_ID = "churn-analytics-473407"
# client = bigquery.Client(project=PROJECT_ID)

# query = "SELECT * FROM churn-analytics-473407.customer_churn.telco_churn"

# df = client.query(query).to_dataframe()

In [ ]:
import pandas as pd
df2 = pd.read_csv("Customer-Churn.csv")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,9426-SXNHE,Female,0,False,False,2,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,False,Bank transfer (automatic),18.75,53.15,False
1,3806-YAZOV,Female,0,False,False,3,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,False,Mailed check,18.80,56,False
2,3387-PLKUI,Female,0,True,True,13,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,False,Mailed check,18.80,251.25,False
3,8992-CEUEN,Female,0,False,False,1,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,False,Electronic check,18.85,18.85,False
4,0620-XEFWH,Male,0,True,True,4,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,False,Mailed check,18.85,84.2,False

In [ ]:
df.shape

(7043, 21)

In [ ]:
df.describe(include="all")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.0,7043,7043,7043.0,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,<NA>,2,2,<NA>,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7569-NMZYQ,Male,<NA>,False,False,<NA>,True,No,Fiber optic,No,...,No,No,No,No,Month-to-month,True,Electronic check,NaN,,False
freq,1,3555,<NA>,3641,4933,<NA>,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.0,NaN,NaN,9.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.0,NaN,NaN,29.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.0,NaN,NaN,55.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.0,NaN,NaN,72.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         Int64
Partner             boolean
Dependents          boolean
tenure                Int64
PhoneService        boolean
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling    boolean
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn               boolean
dtype: object

In [ ]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [ ]:
import pandas as pd
# Convertir la columna a numérica
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

# Revisar si quedaron nulos
print(df["TotalCharges"].isnull().sum())

0

/tmp/ipython-input-3497860044.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

In [ ]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3972,2923-ARZLG,Male,0,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,True,Mailed check,19.70,NaN,False
5532,7644-OMVMY,Male,0,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,19.85,NaN,False
5578,2520-SGTTA,Female,0,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,20.00,NaN,False
5643,3115-CZMZD,Male,0,False,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,20.25,NaN,False
5917,3213-VVOLG,Male,0,True,True,0,True,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,25.35,NaN,False
5956,4367-NUYAO,Male,0,True,True,0,True,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,25.75,NaN,False
6068,4472-LVYGI,Female,0,True,True,0,False,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,True,Bank transfer (automatic),52.55,NaN,False
6104,1371-DWPAZ,Female,0,True,True,0,False,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,False,Credit card (automatic),56.05,NaN,False
6174,2775-SEFEE,Male,0,False,True,0,True,Yes,DSL,Yes,...,No,Yes,No,No,Two year,True,Bank transfer (automatic),61.90,NaN,False
6303,4075-WKNIU,Female,0,True,True,0,True,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,False,Mailed check,73.35,NaN,False
6435,5709-LVOEQ,Female,0,True,True,0,True,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,False,Mailed check,80.85,NaN,False

In [ ]:
# Separamos las variables numericas de las categoricas
categorical_cols = df.select_dtypes(include="object").columns
numerical_cols = df.select_dtypes(include="number").columns

# ahora separamos las variables predictorias de del target
X = df.drop("Churn", axis=1)
y = df["Churn"]

print(X.shape,y.shape)

(7043, 20) (7043,)

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         Int64
Partner             boolean
Dependents          boolean
tenure                Int64
PhoneService        boolean
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling    boolean
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn               boolean
dtype: object

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

numeric_features = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]
categorical_features = [
    "gender", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup",
    "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaymentMethod" ]
boolean_features = ["Partner", "Dependents", "PhoneService", "PaperlessBilling"]

#Preprocesa el dato acorde a su tipo
preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features),
        ("cat", OneHotEncoder(drop="first"), categorical_features),
        ("bool", "passthrough", boolean_features)
    ]
)

# crear pipeline
clf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000,class_weight="balanced"))
])

#separar entre entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# entrenar el modelo
clf.fit(X_train, y_train)

# predecir
y_pred = clf.predict(X_test)

# evaluar
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Accuracy: 0.7366926898509581

Matriz de confusión:
 [[752 283]
 [ 88 286]]

Reporte de clasificación:
               precision    recall  f1-score   support

         0.0       0.90      0.73      0.80      1035
         1.0       0.50      0.76      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.70      1409
weighted avg       0.79      0.74      0.75      1409

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Probabilidades de churn
y_proba = clf.predict_proba(X_test)[:, 1]

# Cambiamos umbral de 0.5 → 0.4
y_pred_custom = (y_proba >= 0.3).astype(int)

print("Matriz de confusión con threshold 0.4:\n", confusion_matrix(y_test, y_pred_custom))
print("\nReporte:\n", classification_report(y_test, y_pred_custom))

Matriz de confusión con threshold 0.4:
 [[574 461]
 [ 40 334]]

Reporte:
               precision    recall  f1-score   support

         0.0       0.93      0.55      0.70      1035
         1.0       0.42      0.89      0.57       374

    accuracy                           0.64      1409
   macro avg       0.68      0.72      0.63      1409
weighted avg       0.80      0.64      0.66      1409

In [ ]:
# ahora probamos con random forest

from sklearn.ensemble import RandomForestClassifier

clf_rf = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=200, random_state=42))
])
clf_rf.fit(X_train, y_train)


y_pred_rf = clf_rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred_rf))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred_rf))

Accuracy: 0.7906316536550745

Matriz de confusión:
 [[925 110]
 [185 189]]

Reporte de clasificación:
               precision    recall  f1-score   support

         0.0       0.83      0.89      0.86      1035
         1.0       0.63      0.51      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [ ]:
#ahora probamos con grandient boosting
from sklearn.ensemble import GradientBoostingClassifier

# 1. Pipeline con Gradient Boosting
clf_gb = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", GradientBoostingClassifier(
        n_estimators=200,     # número de árboles (boosting stages)
        learning_rate=0.1,    # cuánto corrige cada árbol (más bajo = más lento pero más preciso)
        max_depth=3,          # profundidad de cada árbol (pequeños árboles = menos overfitting)
        random_state=42
    ))
])

# 2. Entrenamiento
clf_gb.fit(X_train, y_train)

# 3. Predicción
y_pred_gb = clf_gb.predict(X_test)

# 4. Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred_gb))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred_gb))

Accuracy: 0.7920511000709723
Matriz de confusión:
 [[918 117]
 [176 198]]

Reporte de clasificación:
               precision    recall  f1-score   support

         0.0       0.84      0.89      0.86      1035
         1.0       0.63      0.53      0.57       374

    accuracy                           0.79      1409
   macro avg       0.73      0.71      0.72      1409
weighted avg       0.78      0.79      0.79      1409

# Interpretacion de datos

## Si querés recall (no dejar escapar churners):


*   ### Random Forest gana (89%), aunque la precisión es baja.
*   ### Logistic balanced también es decente (76%).


## Si querés precisión (no gastar en clientes fieles):

*   ### Gradient Boosting gana (63%).


## Si querés equilibrio (F1):

* ### Logistic balanced y Gradient Boosting están muy parejos (~0.6).

* ### Random Forest queda un poco atrás en F1, pero con recall brutal.

In [ ]:
# Por ultimo, ver que variables fueron influyentes en la decision

import numpy as np

# 1. Acceder al preprocesador
preprocessor = clf_gb.named_steps["preprocessor"]

# 2. Nombres de columnas numéricas y booleanas (pasan tal cual)
num_bool_features = numeric_features + boolean_features

# 3. Nombres generados por OneHotEncoder
cat_features = preprocessor.named_transformers_["cat"].get_feature_names_out(categorical_features)

# 4. Juntar todo
feature_names = np.concatenate([num_bool_features, cat_features])

# 5. Importancias desde Gradient Boosting
importances = clf_gb.named_steps["model"].feature_importances_

# 6. DataFrame ordenado
importance = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

print(importance.head(15))

                               feature  importance
1                               tenure    0.264749
7                     PaperlessBilling    0.168896
3                         TotalCharges    0.117778
24                 StreamingMovies_Yes    0.105758
2                       MonthlyCharges    0.094055
22                     StreamingTV_Yes    0.075203
21     StreamingTV_No internet service    0.049707
29          PaymentMethod_Mailed check    0.025503
10                   MultipleLines_Yes    0.015625
16                    OnlineBackup_Yes    0.009216
20                     TechSupport_Yes    0.008999
0                        SeniorCitizen    0.008771
8                          gender_Male    0.007290
18                DeviceProtection_Yes    0.006214
13  OnlineSecurity_No internet service    0.006123